### ISSUE TITLE
Scan quote does not work properly

### ISSUE THREAD

**Issue by b1acKr0se** [voz-living/chrome-extension-react#24]
Seems that the string literals comparison of username is off.

My username is `Fatality.`, but the extension notifies me whenever the word `fatality` comes up in a post. It does not take into account the case sensitive or fully matching the word. The post doesn't necessarily contain a quote either.

Now I don't know the algorithm behind this and my JS knowledge is lackluster, but after inspect the structure of a post, how about implementing it like this:

1. Scan the content of the post.
2. Find the string "Originally Posted by ". (if you have access to the html element then this will be much more accurate).
3. Get the username that comes after.
4. Do the string comparison.

I'm sorry if this is not feasible since I didn't consider any constraints you might have, or that it has been done in this way already. 

Thank you.

**Comment by thang-hoang** [comment]
Hi Hai,

Thank you for your report, we are looking into it now, will apply some patch when we found the problem(s).

Once again, thank you for using voz-living

Best Regards,
Clark Hoang

**Comment by phonglk** [comment]
The new version have a better way to handling quote notification. Please help to check it out!

**Comment by b1acKr0se** [comment]
Alright, will keep an eye on it.
