### ISSUE TITLE
Add support video for dantri

### ISSUE THREAD

**Issue by phonglk** [voz-living/chrome-extension-react#36]
Link post https://vozforums.com/showthread.php?t=6467753

Link video: http://vcplayer.mediacdn.vn/1.1/?_site=dantri&vid=dantri/85b8ad95ea/2017/09/06/dinh-tac-bac-ninh-2-1504699539637.mp4&_info=54eaea941a2d4788aa7019b3c8d3c065&mute=false&vtype=1&playType=0&_admParamTvc=0;0;0;0&_listsuggest=http://wcm.dantri.com.vn/video/zone-2/suggest-videos.htm&postroll=true&replay=true&nonVol=true&volume=0&boxVideoID=ifVideo-69180&nopre=true&midroll=0.8;20s

**Comment by SuperDOgePx** [comment]
Lỗi phía server-side, không thể fix được.
![image](https://user-images.githubusercontent.com/30575847/33125339-aa5334e4-cfb2-11e7-8cff-dd20ef361ab5.png)

**Comment by SuperDOgePx** [comment]
Issue resolved
