### ISSUE TITLE
lỗi Quotes

### ISSUE THREAD

**Issue by Phongdq** [voz-living/chrome-extension-react#49]
Gần đây mình hay nhận được thông báo quotes, mà ko phải quotes của mình (của người khác), trong thread mình cũng ko bao giờ comment. Các thím kiểm tra lại nhé. 

![quotes](https://user-images.githubusercontent.com/15854145/32587721-916311d2-c53c-11e7-9be6-e91687454f7c.jpg)

Thớt này, mình cũng ko subscribe hay follow gì gì cả: [https://vozforums.com/showthread.php?p=129828309#post129828309](url)

**Comment by phonglk** [comment]
Bản mới khắc phục được rồi nha bạn
